export type SeedRecord = {
  registry_id: string;
  entity_type: string;
  name: string;
  acronym?: string;
  description?: string;
  category?: string;
  province?: string;
  address?: string;
  website?: string;
  primary_email?: string;
  primary_phone?: string;
  gps_lat?: number;
  gps_lng?: number;
  metadata?: Record<string, unknown>;
  tags?: string[];
};

export const REGISTRY_SEED_DATA: SeedRecord[] = [
  // Government
  {
    registry_id: "REG-NA-GOV-001",
    entity_type: "government",
    name: "Ministry of Finance and Public Enterprises",
    acronym: "MOFPE",
    description: "Central ministry responsible for fiscal policy and public enterprise oversight.",
    category: "Ministry",
    province: "Khomas",
    address: "Corner of Luther and Robert Mugabe Avenue, Windhoek",
    website: "https://www.mof.gov.na",
    primary_email: "info@mof.gov.na",
    primary_phone: "+26461209511",
    gps_lat: -22.5594,
    gps_lng: 17.0836,
    metadata: {
      minister: "Hon. Iipumbu Shiimi",
      departments: ["Budget", "Treasury", "SOE Oversight"],
      employees: 450,
      public_services: ["Tax Registration", "Budget Reports"],
      regulatory_authority: "Public Enterprises Governance Act",
    },
    tags: ["ministry", "finance"],
  },
  {
    registry_id: "REG-NA-GOV-002",
    entity_type: "government",
    name: "Supreme Court of Namibia",
    acronym: "SCN",
    description: "Highest court of appeal in Namibia.",
    category: "Court",
    province: "Khomas",
    address: "Corner of John Meinert and Rehobother Street, Windhoek",
    primary_phone: "+26461293333",
    metadata: { minister: "Chief Justice", employees: 85 },
    tags: ["court", "judiciary"],
  },
  {
    registry_id: "REG-NA-GOV-003",
    entity_type: "government",
    name: "City of Windhoek",
    acronym: "CoW",
    description: "Capital city municipality.",
    category: "Municipality",
    province: "Khomas",
    address: "Corner of Independence Avenue and John Meinert Street",
    website: "https://www.windhoekcc.org.na",
    primary_email: "info@windhoekcc.org.na",
    primary_phone: "+264612902011",
    metadata: { public_services: ["Rates", "Building Permits", "Water Services"] },
    tags: ["municipality", "khomas"],
  },
  {
    registry_id: "REG-NA-GOV-004",
    entity_type: "government",
    name: "Namibia Financial Institutions Supervisory Authority",
    acronym: "NAMFISA",
    description: "Non-banking financial institutions regulator.",
    category: "Regulator",
    province: "Khomas",
    website: "https://www.namfisa.com.na",
    primary_email: "info@namfisa.com.na",
    tags: ["regulator", "finance"],
  },
  {
    registry_id: "REG-NA-GOV-005",
    entity_type: "government",
    name: "TransNamib Holdings",
    acronym: "TRANSNAMIB",
    description: "State-owned rail and logistics operator.",
    category: "State-Owned Enterprise",
    province: "Khomas",
    address: "Railway Street, Windhoek",
    website: "https://www.transnamib.com.na",
    metadata: { employees: 2400, public_services: ["Freight", "Passenger Rail"] },
    tags: ["soe", "transport"],
  },
  // Banking
  {
    registry_id: "REG-NA-BNK-001",
    entity_type: "banking",
    name: "Bank Windhoek",
    acronym: "BWH",
    description: "Leading commercial bank in Namibia.",
    category: "Commercial Bank",
    province: "Khomas",
    address: "Independence Avenue, Windhoek",
    website: "https://www.bankwindhoek.com.na",
    primary_email: "info@bankwindhoek.com.na",
    primary_phone: "+26461299501",
    metadata: {
      swift: "BWLINANX",
      branches: 52,
      executives: ["Baronice Hanspaach - MD"],
      financial_licenses: ["BoN Commercial Banking License"],
      digital_banking: ["Internet Banking", "Mobile App"],
      mobile_apps: ["Bank Windhoek App"],
    },
    tags: ["bank", "commercial"],
  },
  {
    registry_id: "REG-NA-BNK-002",
    entity_type: "banking",
    name: "Standard Bank Namibia",
    acronym: "SBN",
    description: "Major commercial bank subsidiary.",
    category: "Commercial Bank",
    province: "Khomas",
    website: "https://www.standardbank.com.na",
    metadata: { swift: "SBNMNANX", branches: 28 },
    tags: ["bank", "commercial"],
  },
  {
    registry_id: "REG-NA-BNK-003",
    entity_type: "banking",
    name: "Development Bank of Namibia",
    acronym: "DBN",
    description: "National development finance institution.",
    category: "Development Bank",
    province: "Khomas",
    website: "https://www.dbn.com.na",
    metadata: { financial_licenses: ["Development Finance License"] },
    tags: ["bank", "development"],
  },
  {
    registry_id: "REG-NA-BNK-004",
    entity_type: "banking",
    name: "FNB Namibia",
    acronym: "FNB",
    description: "First National Bank Namibia operations.",
    category: "Commercial Bank",
    province: "Khomas",
    metadata: { swift: "FIRNNANX", branches: 35, mobile_apps: ["FNB App"] },
    tags: ["bank", "commercial"],
  },
  {
    registry_id: "REG-NA-BNK-005",
    entity_type: "banking",
    name: "PayToday",
    acronym: "PAYTODAY",
    description: "Digital payment platform.",
    category: "Payment Platform",
    province: "Khomas",
    website: "https://www.paytoday.com.na",
    metadata: { digital_banking: ["QR Payments", "Merchant Services"] },
    tags: ["payments", "fintech"],
  },
  // Healthcare
  {
    registry_id: "REG-NA-HLT-001",
    entity_type: "healthcare",
    name: "Windhoek Central Hospital",
    acronym: "WCH",
    description: "National referral hospital.",
    category: "Hospital",
    province: "Khomas",
    address: "Corner of Robert Mugabe Ave and Hans-Dietrich Genscher St",
    primary_phone: "+264612033000",
    gps_lat: -22.5642,
    gps_lng: 17.0858,
    metadata: { beds: 855, emergency_services: true, ownership: "Public", doctors: 120, staff: 2100 },
    tags: ["hospital", "referral"],
  },
  {
    registry_id: "REG-NA-HLT-002",
    entity_type: "healthcare",
    name: "Katutura Intermediate Hospital",
    acronym: "KIH",
    description: "Major public hospital in Katutura.",
    category: "Hospital",
    province: "Khomas",
    metadata: { beds: 610, emergency_services: true, ownership: "Public" },
    tags: ["hospital"],
  },
  {
    registry_id: "REG-NA-HLT-003",
    entity_type: "healthcare",
    name: "PathCare Namibia",
    acronym: "PATHCARE",
    description: "Private pathology laboratory network.",
    category: "Laboratory",
    province: "Khomas",
    website: "https://www.pathcare.co.za",
    metadata: { ownership: "Private", regulatory_status: "MoHSS Licensed" },
    tags: ["laboratory"],
  },
  {
    registry_id: "REG-NA-HLT-004",
    entity_type: "healthcare",
    name: "Ministry of Health and Social Services",
    acronym: "MoHSS",
    description: "National healthcare authority.",
    category: "Healthcare Authority",
    province: "Khomas",
    website: "https://www.mhss.gov.na",
    tags: ["authority", "government"],
  },
  // Infrastructure
  {
    registry_id: "REG-NA-INF-001",
    entity_type: "infrastructure",
    name: "NamPower",
    acronym: "NAMPOWER",
    description: "National power utility.",
    category: "Energy Infrastructure",
    province: "Khomas",
    address: "15 Luther Street, Windhoek",
    website: "https://www.nampower.com.na",
    primary_phone: "+264612041111",
    metadata: {
      operator: "NamPower Ltd",
      capacity: "500 MW",
      criticality_rating: "critical",
      service_areas: ["National Grid"],
    },
    tags: ["energy", "utility"],
  },
  {
    registry_id: "REG-NA-INF-002",
    entity_type: "infrastructure",
    name: "Namibia Stock Exchange",
    acronym: "NSX",
    description: "National securities exchange.",
    category: "Stock Exchange",
    province: "Khomas",
    website: "https://www.nsx.com.na",
    metadata: { operator: "NSX Ltd", criticality_rating: "high" },
    tags: ["finance", "exchange"],
  },
  {
    registry_id: "REG-NA-INF-003",
    entity_type: "infrastructure",
    name: "Telecom Namibia",
    acronym: "TN",
    description: "National telecom infrastructure operator.",
    category: "Telecom Infrastructure",
    province: "Khomas",
    website: "https://www.telecom.na",
    metadata: { operator: "Telecom Namibia Ltd", criticality_rating: "critical" },
    tags: ["telecom"],
  },
  {
    registry_id: "REG-NA-INF-004",
    entity_type: "infrastructure",
    name: "Walvis Bay Port",
    acronym: "WBP",
    description: "Primary Atlantic seaport.",
    category: "Port",
    province: "Erongo",
    metadata: { operator: "Namport", capacity: "Container + Bulk", criticality_rating: "critical" },
    tags: ["port", "logistics"],
  },
  {
    registry_id: "REG-NA-INF-005",
    entity_type: "infrastructure",
    name: "Hosea Kutako International Airport",
    acronym: "HKIA",
    description: "Primary international airport.",
    category: "Airport",
    province: "Khomas",
    metadata: { operator: "Namibia Airports Company", criticality_rating: "critical" },
    tags: ["airport", "aviation"],
  },
  // Business
  {
    registry_id: "REG-NA-BIZ-001",
    entity_type: "business",
    name: "Namibia Breweries Limited",
    acronym: "NBL",
    description: "Leading beverage manufacturer.",
    category: "Manufacturing",
    province: "Khomas",
    website: "https://www.nbl.com.na",
    metadata: {
      registration_number: "1957/001",
      tax_id: "VAT-001",
      industry: "Beverages",
      employees: 450,
      compliance_status: "Compliant",
    },
    tags: ["manufacturing", "listed"],
  },
  {
    registry_id: "REG-NA-BIZ-002",
    entity_type: "business",
    name: "MTC Namibia",
    acronym: "MTC",
    description: "Mobile telecommunications company.",
    category: "Technology",
    province: "Khomas",
    website: "https://www.mtc.com.na",
    metadata: { registration_number: "1992/003", tax_id: "VAT-MTC", employees: 800, industry: "Telecom" },
    tags: ["telecom", "listed"],
  },
  {
    registry_id: "REG-NA-BIZ-003",
    entity_type: "business",
    name: "Ohorongo Cement",
    acronym: "OHORONGO",
    description: "Cement manufacturing.",
    category: "Manufacturing",
    province: "Otjozondjupa",
    metadata: { registration_number: "2007/012", industry: "Construction Materials", employees: 350 },
    tags: ["manufacturing"],
  },
  // Citizens (metadata holds sensitive refs — full PII in encrypted directory)
  {
    registry_id: "REG-NA-CIT-001",
    entity_type: "citizen",
    name: "Johannes Chirongo",
    category: "Citizen Record",
    province: "Khomas",
    primary_phone: "+264811234441",
    primary_email: "johannes.chirongo@email.na",
    metadata: {
      national_id: "85031500123",
      date_of_birth: "1985-03-15",
      employment: "Private Sector",
      digital_identity_status: "Unclaimed",
      sim_verification: "Pending",
      consent_status: "Required",
      directory_record_id: "11111111-1111-4111-8111-111111111001",
    },
    tags: ["citizen"],
  },
  {
    registry_id: "REG-NA-CIT-002",
    entity_type: "citizen",
    name: "Maria Nghidinwa",
    category: "Citizen Record",
    province: "Erongo",
    primary_phone: "+264812345678",
    primary_email: "maria.n@email.na",
    metadata: {
      national_id: "90072200456",
      date_of_birth: "1990-07-22",
      digital_identity_status: "Unclaimed",
      consent_status: "Required",
      directory_record_id: "11111111-1111-4111-8111-111111111002",
    },
    tags: ["citizen"],
  },
];
